## Difference
+ Size Imbalance, where the data size on each device (or client) is uneven; 
+ LocalImbalance, i.e.,independentandnon-identicallydistribution (non-IID), where each device does not follow a common data distribution;
+ Global Imbalance, means that the collection of data in all devices is class imbalanced.

In [1]:
import DataProcessor
#import DataBalance
import numpy as np 
from importlib import reload

In [2]:
reload(DataProcessor)
#reload(DataBalance)

<module 'DataProcessor' from '/Users/xinhey/Desktop/federated-learning-master 2/DataProcessor.py'>

In [3]:
dp = DataProcessor.DataProcessor()

In [4]:
# ds.get_input('cifar')
dp.get_input('mnist')

In [10]:
dp.train_label.shape

(60000,)

In [11]:
dp.train_feature[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [154]:
print(dp.train_feature.shape)
print(dp.test_feature.shape)
print(dp.train_label.shape)
print(dp.test_label.shape)

(60000, 784)
(10000, 784)
(60000,)
(10000,)


In [155]:
dp.get_local_difference(dp.train_label.reshape(5, -1))

array([[0.        , 0.00050825, 0.0004306 , 0.0004014 , 0.00063494],
       [0.00050649, 0.        , 0.00021708, 0.00037013, 0.00091191],
       [0.00043047, 0.00021605, 0.        , 0.000169  , 0.0008503 ],
       [0.00040381, 0.00036918, 0.00016936, 0.        , 0.00049898],
       [0.00063467, 0.00090463, 0.00084091, 0.00049606, 0.        ]])

In [156]:
dp.get_global_difference(dp.train_label)

[5421, 5842, 5851, 5918, 5923, 5949, 5958, 6131, 6265, 6742]

In [16]:
dp.gen_local_imbalance(10, 5000, 0)

In [158]:
dp.get_global_difference(dp.global_train_label)

[4481, 4853, 4858, 4925, 4939, 4941, 5052, 5091, 5244, 5616]

In [19]:
len(dp.local_train_label[0])

5000

In [107]:
db = DataBalance.DataBalance(dp)

In [108]:
dp.local_train_label

[array([9, 9, 7, ..., 3, 9, 9]),
 array([4, 4, 8, ..., 6, 3, 7]),
 array([3, 8, 9, ..., 3, 4, 0]),
 array([9, 7, 5, ..., 1, 6, 9]),
 array([6, 5, 4, ..., 3, 5, 1]),
 array([6, 6, 0, ..., 7, 7, 6]),
 array([3, 8, 7, ..., 0, 7, 2]),
 array([3, 6, 0, ..., 6, 8, 4]),
 array([4, 3, 3, ..., 5, 1, 0]),
 array([1, 1, 1, ..., 1, 6, 8])]

In [109]:
r_ad = np.zeros(dp.size_class)

# 3 : Calculate the data size of each class C
num_each_class = np.zeros(dp.size_class)
for i in dp.global_train_label:
    num_each_class[i] = num_each_class[i] + 1

# 4 : Calculate the mean m and the standard deviation s of C
mean = np.mean(num_each_class)
std = np.std(num_each_class, ddof=1)
# 5 : Calculate the z-score
z = (num_each_class- mean) / std

In [110]:
z

array([-0.27986367,  2.21472359, -0.07601235,  0.48025987, -0.5424518 ,
       -1.62390029, -0.2936841 ,  0.68411119, -0.5424518 , -0.02073064])

In [111]:
db.td = 0.1
db.ta = - 0.1

In [112]:
db.z_score()

size: 0
the 0th feature
the 1000th feature
the 2000th feature
the 3000th feature
the 4000th feature
size: 1
the 0th feature
the 1000th feature
the 2000th feature
the 3000th feature
the 4000th feature
size: 2
the 0th feature
the 1000th feature
the 2000th feature
the 3000th feature
the 4000th feature
size: 3
the 0th feature
the 1000th feature
the 2000th feature
the 3000th feature
the 4000th feature
size: 4
the 0th feature
the 1000th feature
the 2000th feature
the 3000th feature
the 4000th feature
size: 5
the 0th feature
the 1000th feature
the 2000th feature
the 3000th feature
the 4000th feature
size: 6
the 0th feature
the 1000th feature
the 2000th feature
the 3000th feature
the 4000th feature
size: 7
the 0th feature
the 1000th feature
the 2000th feature
the 3000th feature
the 4000th feature
size: 8
the 0th feature
the 1000th feature
the 2000th feature
the 3000th feature
the 4000th feature
size: 9
the 0th feature
the 1000th feature
the 2000th feature
the 3000th feature
the 4000th feature


In [113]:
dp.get_global_difference(dp.global_train_label)

[4919, 4931, 4933, 4951, 4953, 4978, 4994, 5048, 5070, 5140]

In [114]:
db.assign_clients()

In [115]:
db.mediator

[{7, 8, 9}, {4, 5, 6}, {1, 2, 3}, {0}]

In [12]:
dp.gen_size_imbalance([5000, 2000, 1000])

AttributeError: 'DataProcessor' object has no attribute 'size_label'

In [74]:
dp.get_global_difference(dp.global_train_label)

[765, 765, 792, 796, 806, 809, 809, 809, 817, 832]

In [75]:
dp.get_local_difference(dp.local_train_label)

array([[0.        , 0.00223889, 0.00587034],
       [0.00225046, 0.        , 0.00422742],
       [0.00584834, 0.00407691, 0.        ]])

In [76]:
dp.get_size_difference(dp.local_train_label)

the 0th device size: 5000
the 1th device size: 2000
the 2th device size: 1000


In [159]:
dp.gen_global_imbalance(5, 2000, [500, 500, 1000, 1000, 1500, 1500, 3000, 1000, 0, 0])

In [160]:
dp.get_global_difference(dp.global_train_label)

[0, 0, 500, 500, 1000, 1000, 1000, 1500, 1500, 3000]

In [161]:
dp.get_local_difference(dp.local_train_label)

array([[0.        , 0.0031424 , 0.0042759 , 0.00159083, 0.00345882],
       [0.00309214, 0.        , 0.00155139, 0.00162139, 0.0021397 ],
       [0.00429454, 0.00153019, 0.        , 0.00215769, 0.00215751],
       [0.00168137, 0.00165244, 0.00215916, 0.        , 0.00308114],
       [0.00346902, 0.00210147, 0.00219588, 0.0030836 , 0.        ]])